version: '3'

services:
  postgres:
    image: postgres:14
    container_name: pg_sandbox
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    ports:
      - '6789:5432'
    command: postgres -c 'max_prepared_transactions=100'
